name: Build and deploy Node.js app to Azure Web App - front-ecom-proje

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Archive production artifacts
        run: |
          mkdir release
          xcopy .next release\.next /E /H /C /I
          xcopy public release\public /E /H /C /I
          copy next.config.mjs release\
          copy package.json release\
          copy package-lock.json release\
          tar -czf release.tar.gz -C release .
        shell: bash

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.tar.gz

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: tar -xzf release.tar.gz

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'front-ecom-proje'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EC3891AB8589478E9901061FF988E453 }}
          package: .
