name: Build and deploy Node.js app to Azure Web App - front-ecom-projet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: Archive production artifacts
        run: |
          mkdir -p release
          cp -r .next release/
          cp -r public release/
          cp package.json release/
          cp package-lock.json release/
          cd release
          zip -r ../release.zip .
        shell: bash

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'front-ecom-projet'  # Assurez-vous que le nom est correct
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A31F29A824B443E8AE4DFA49CA00FB90 }}
          package: .

      - name: Fetch Azure logs if deployment fails
        if: failure()
        run: |
          echo "Fetching logs from Azure App Service"
          az webapp log download --resource-group DefaultResourceGroup-PAR --name front-ecom-projet --log-file logs.zip
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload Azure logs if deployment fails
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: azure-logs
          path: logs.zip
